### ISSUE TITLE
how change notification small icon for android in flutter

### ISSUE THREAD

**Issue by somkar99** [Pushwoosh/pushwoosh-flutter#29]
the notification icon is picking up the app icon, want to set a custom icon for the android notification

**Comment by wfhm** [comment]
@somkar99,

Just put your icon file in your **android/app/src/main/res/drawable** directory and rename it to **pw_notification.png**. The icon will automatically be used as a default notification icon. Please make sure that the icon uses alpha-channel only and has a transparent background, otherwise it will be shown as a white square/circle.
