### ISSUE TITLE
Upgrade androidx.work:work-runtime version in android

### ISSUE THREAD

**Issue by teknofreek** [Pushwoosh/pushwoosh-flutter#48]
There is this error in build

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkReleaseAarMetadata'.
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not resolve androidx.work:work-runtime:[2.0.0, 2.7.99].
     Required by:
         project :app > project :pushwoosh > com.pushwoosh:pushwoosh:6.4.1
      > Failed to list versions for androidx.work:work-runtime.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/androidx/work/work-runtime/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/androidx/work/work-runtime/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/androidx/work/work-runtime/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

I am able to fix it by adding the following to the library's build.gradle dependencies section

```
    constraints {
        implementation('androidx.work:work-runtime') {
          version {
            strictly '2.7.0'
            }
        }
    }
```

It would be good to fix it in the library.

**Comment by wfhm** [comment]
@teknofreek 

The problem is that a plugin (location in this case) didn't specify a fixed version of an Android library. So in order to find which versions are available, Gradle must go to the repository to check. In this case, that repository is Bintray, which has been down for days and returning HTTP 502 Bad Request.

We are looking for a reliable workaround, meanwhile, you can either keep specifying any particular version or try the solution described in the Flutter repo:

https://github.com/flutter/flutter/issues/94400#issuecomment-995258623

**Comment by wfhm** [comment]
@teknofreek It seems the issue is not reproducible anymore if you replace the`jcenter()` repository with `mavenCentral()` in your build.gradle. Could you please let me know if the issue persists in your project? If yes, do you still use` jcenter()` in your project, and what is your gradle plugin's version?
