### ISSUE TITLE
Android: icon not showed correctly on received push 

### ISSUE THREAD

**Issue by lucaslombardif** [Pushwoosh/pushwoosh-flutter#53]
I configured the application correctly in the panel, but the icon is not displayed as expected. What is displayed is just a gray square.

Upon receiving the notification, I noticed the following error:

```
[Asset] File not found: assets/www/res/default 
```

Follow the images for illustrate this:

<img width="250" alt="gray_square_error" src="https://user-images.githubusercontent.com/23706340/181357730-c0f2710f-7397-4423-9537-67be52b8cb5e.png">
<img width="673" alt="pushwoosh_error" src="https://user-images.githubusercontent.com/23706340/181357734-3c97bef4-eced-43c8-8c6e-b9d7d10cc907.png">

Pushwoosh library version: 2.2.6

Flutter doctor summary output: 
``` 
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [versÆo 10.0.19043.1826], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Ferramentas de Build do Visual Studio 2017 15.9.45)
    X Visual Studio 2019 or later is required.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.69.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 1 category.
```

**Comment by wfhm** [comment]
@lucaslombardif hi,

Actually the exception in the console is related to a default notification sound, not to an icon, and it was fixed with the latest release. 

The icon issue is most likely explained by how Android draws icons in status bar - it ignores all channels except for an alpha-channel and draws it in a single color (usually gray or white). It also means that if your icon does not have a transparent background, it will be shown as a white/gray square (all colors are changed to white/gray, including background colors, so you effectively just get a square).

To solve your issue, you should create your icons according to Android Material design guidelines:
https://material.io/design/platform-guidance/android-icons.html

You can also refer to this [guide](
https://docs.pushwoosh.com/platform-docs/pushwoosh-sdk/android-push-notifications/customizing-android-sdk/android-faq#how-to-set-a-notification-icon-in-android-lollipop-and-later-versions) and use [AndroidAssetStudio](https://romannurik.github.io/AndroidAssetStudio/) to create a set of icons that conform to Android guidelines

**Comment by lucaslombardif** [comment]
Hi @wfhm,

Thank you very much.
