### ISSUE TITLE
Cannot handle push from flutter when app in background

### ISSUE THREAD

**Issue by vanphuc3112** [Pushwoosh/pushwoosh-flutter#9]
I had implement following guideline:
1. call `Pushwoosh.initialize()`
2. set `Pushwoosh.getInstance.onPushReceived`
3. set `Pushwoosh.getInstance.onPushAccepted`
4. call `Pushwoosh.getInstance.registerForPushNotifications()`
When app is in foreground, calling from `onPushReceived` and `onPushAccepted` is ok.
but when I switch app to background, push has been sent to Notification Tray successfully, but event on `onPushReceived` and `onPushAccepted` is not work.
Could you guide me how to handle push when app in background.
Thank you!

**Comment by wfhm** [comment]
Hi @vanphuc3112,

> when I switch app to background, push has been sent to Notification Tray successfully, but event on `onPushReceived`and `onPushAccepted` is not work.

`onPushAccepted` callback is designed to fire only when a notification is handled - either when a notification is clicked or automatically handled in foregrounded app.

Since in iOS pushes are received and notifications are shown by the OS itself, applications do not "know" a push was actually received unless you open your app via clicking on a notification (or unless your app is already running in foreground). This means that `onPushReceived` callback will only fire instantly when pushes are received in foreground or when you bring your app in foreground state by clicking on a push notification.

Could you please clarify whether `onPushAccepted` callback does not fire when you click on a notification, or just when a push is received?

**Comment by vanphuc3112** [comment]
Hi @wfhm 
I know `onPushAccepted` will be called when we click on the notification. But when app is in background (on Android, I opened multitask and swipe to close my app), and when push received, I click on the notification, app opened but `onPushAccepted` was not been called.

**Comment by wfhm** [comment]
@vanphuc3112,

Got it, checking it. Meanwhile, could you please specify whether the issue affects Android only or both iOS and Android?

**Comment by vanphuc3112** [comment]
@wfhm 
it effect on both iOS and Android.
Thanks for your supporting.

**Comment by wfhm** [comment]
@vanphuc3112

Fixed with the latest release.

**Comment by vanphuc3112** [comment]
Great, it work ok now.
Many thanks for your supporting :)
